### ISSUE TITLE
batdetect2

### ISSUE THREAD

**Issue by SarahDal** [acoupi/acoupi#71]
Hia, Is the acoupi_batdetect2 repo still available for use? The links are 404s and pip can't find the distribution.

**Comment by mbsantiago** [comment]
Hi @SarahDal! We have not yet made the acoupi_batdetect2 repo public, but will do so this week!

**Comment by SarahDal** [comment]
Brilliant, thank you!

**Comment by mbsantiago** [comment]
Hi @SarahDal. The `acoupi_batdetect2` repo is now public and its documentation is live. Let us know if you have any questions :)
