### ISSUE TITLE
Batedetect2 - python version

### ISSUE THREAD

**Issue by SarahDal** [acoupi/acoupi#72]
Really keen to get going with this! First installation issue -

```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python <3.11,>=3.9
ERROR: Could not find a version that satisfies the requirement acoupi_batdetect2 (from versions: none)
ERROR: No matching distribution found for acoupi_batdetect2
```

I have python 3.11.2 installed, is this an error or do I need to revert to an earlier version of python?

**Comment by mbsantiago** [comment]
Hey @SarahDal, I believe you can now install acoupi and acoupi_batdetect2 on python 3.12. Batdetect2 used to restrict versions to <3.12 but we updated that recently. Let us know if it works!

**Comment by audevuilli** [comment]
@SarahDal That’s great to hear! 😊 Enjoy seeing messages coming through your MQTT feed—hopefully you will get some if you’re in an area with bats around. You’re actually our first user, as only people from our team have used it so far.

So, please don’t hesitate to share your feedback! We’d love to hear about your experience setting it up on your Raspberry Pi. Let us know if there are any features you’d like to see, anything that felt confusing, or areas where we could improve. We hope the project will grow with its users, so any insights would be incredibly valuable. 😃
