### ISSUE TITLE
Errors when running BatDetect2

### ISSUE THREAD

**Issue by SarahDal** [acoupi/acoupi#74]
The Acoupi Connected program works as expected and send mqtt keep alive messages. However when I set up and run BatDetect2, no mqtt are received, and I get the following on stopping
```
Stopping acoupi...
Removed "/home/pi/.config/systemd/user/default.target.wants/acoupi.service".
Removed "/home/pi/.config/systemd/user/default.target.wants/acoupi-beat.service".
Running file_management_task to manage 236 remaining files in the temporary directory.
Running messaging task to send remaining messages.
Running detection_task on remaining 236.
/home/pi/venv/lib/python3.11/site-packages/joblib/_multiprocessing_helpers.py:46: UserWarning: [Errno 28] No space left on device.  joblib will operate in serial mode
  warnings.warn('%s.  joblib will operate in serial mode' % (e,))
Killed
```
There is physical space on the SD card; is it referring to RAM? I've attached the logs

[beat.log](https://github.com/user-attachments/files/17997613/beat.log)
[default.log](https://github.com/user-attachments/files/17997614/default.log)
[recording.log](https://github.com/user-attachments/files/17997615/recording.log)

**Comment by audevuilli** [comment]
Hi @SarahDal, 

Looking through your .log files it seems that you configuration for the acoupi_batdetect2 program is doing continuous recording. Did you set the recording.interval parameter to 0? 

You can check this by entering the command `acoupi config get --field recording.interval` . If this value is set to 0, you might want to change it back to the default value of 10 using the command `acoupi config set --field recording.interval 10`.  

Currently running the inference of the batdetect2 model on the RPi takes around 5 seconds. If recordings are happening consecutively, the detection_task is struggling to process all the files coming through and get stuck. The recordings files then piled up in the temporary memory (RAM). 

If you haven't shutdown your RPi, check that the recordings file in the temporary memory are deleted before restarting an acoupi program, as having the files still in your RAM won't allow you to record anymore. 

To check if there are files in temporary memory use the command: `ls /run/shm/`. 

Would be great to know your recording configuration of the program to help you will fixing your issue :-)

**Comment by SarahDal** [comment]
Hi @audevuilli 

apologies, I thought I'd replied to this last week! I'm currently running the batdetect2 with the following config:

`{
  "timezone": "Europe/London",
  "microphone": {
    "device_name": "384kHz AudioMoth USB Microphone",
    "samplerate": 384000,
    "audio_channels": 1
  },
  "recording": {
    "duration": 3,
    "interval": 20,
    "chunksize": 8192,
    "schedule_start": "16:00:00",
    "schedule_end": "07:00:00"
  },
  "paths": {
    "tmp_audio": "/run/shm",
    "recordings": "/home/pi/storages/recordings",
    "db_metadata": "/home/pi/storages/metadata.db"
  },
  "messaging": {
    "messages_db": "/home/pi/storages/messages.db",
    "message_send_interval": 120,
    "heartbeat_interval": 600,
    "http": null,
    "mqtt": {
      "host": "192.168.0.xx",
      "username": "mqqt",
      "password": "password",
      "topic": "acoupi",
      "port": 1883,
      "timeout": 5
    }
  },
  "detections": {
    "threshold": 0.2
  },
  "model": {
    "detection_threshold": 0.4
  },
  "saving_filters": {
    "starttime": "16:00:00",
    "endtime": "07:00:00",
    "before_dawndusk_duration": 0,
    "after_dawndusk_duration": 0,
    "frequency_duration": 0,
    "frequency_interval": 0,
    "saving_threshold": 0.3
  },
  "saving_managers": {
    "true_dir": "bats",
    "false_dir": "no_bats",
    "timeformat": "%Y%m%d_%H%M%S",
    "bat_threshold": 0.5
  },
  "summariser_config": {
    "interval": 3600.0,
    "low_band_threshold": 0.0,
    "mid_band_threshold": 0.0,
    "high_band_threshold": 0.0
  }
}
`

I'm not getting any heartbeat mqtt messages either, although I do when I run just the acoupi connected program

**Comment by SarahDal** [comment]
Very please to say that I just ran a completely fresh install and it's working! I'm getting detections sent through MQTT.. although it is reporting a fair few lesser noctules in my living room.

**Comment by audevuilli** [comment]
Dear @SarahDal, 

Great to hear a fresh install solves your issues! :-) 

Regarding finding lesser noctules in your living room, I am not that surprised! When testing the batdetect2 model on my desk with a detection_threshold of 0.3/0.4 I also detected a few bats species. Also none are flying around the lab. 

Low confidence thresholds for detection and classification will give you some false_positive. I would recommend you to familiarise yourself with the figure 3 on page 11 of the paper discussing the BatDetect2 model  ["Towards a general approach for Bat Echolocation Detection and Classification" by Mac Aodha et al. (2022)](https://www.biorxiv.org/content/10.1101/2022.12.14.520490v1). The figures shows the precision-recall curves for each species. You will notice that the Nyctalus and Myotis genus are where the algorithm performance is lowest. 

Hope that's helpful!
